# Debug Options
CONFIG_INIT_STACKS=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_IPC_SERVICE_LOG_LEVEL_INF=y

# Compiler Options
CONFIG_DEBUG_OPTIMIZATIONS=y

# Netcore Options
CONFIG_SOC_NRF53_CPUNET_ENABLE=y

# IPC Options
CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_RPMSG=y
CONFIG_OPENAMP=y
CONFIG_OPENAMP_MASTER=y
CONFIG_OPENAMP_SLAVE=n

CONFIG_LOG=y
CONFIG_LOG_OUTPUT=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD=y
CONFIG_LOG_MULTIDOMAIN=y
CONFIG_LOG_LINK_IPC_SERVICE=y
CONFIG_LOG_BACKEND_IPC_SERVICE=n
CONFIG_LOG_PROCESSING_LATENCY_US=100000
