set(NET_APP multidomain_netcore)

ExternalZephyrProject_Add(
    APPLICATION ${NET_APP}
    SOURCE_DIR  ${APP_DIR}/${NET_APP}
    BOARD       nrf5340dk/nrf5340/cpunet
)

set_property(GLOBAL APPEND PROPERTY PM_DOMAINS CPUNET)
set_property(GLOBAL APPEND PROPERTY PM_CPUNET_IMAGES ${NET_APP})
set_property(GLOBAL PROPERTY DOMAIN_APP_CPUNET ${NET_APP})
set(CPUNET_PM_DOMAIN_DYNAMIC_PARTITION ${NET_APP} CACHE INTERNAL "")
